In [1]:
import numpy
dizi=numpy.array([1,2,3,4])
print(dizi)

[1 2 3 4]


In [2]:
import numpy as np
dizi=np.array([1,2,3,4])
print(dizi)

[1 2 3 4]


In [3]:
dizi1=np.array(['A','B','C'])
print(dizi1)
print(type(dizi1)) #Numpy ile oluşturulan dizi nesnelerine ndarray adı verilir...

['A' 'B' 'C']
<class 'numpy.ndarray'>


In [4]:
diziTuple=np.array((12,25,26))
print(diziTuple)

[12 25 26]


In [5]:
#0 Boyutlu bir dizi oluşturma
diziSifir=np.array(25)
print(diziSifir)

25


In [6]:
#Tek boyutlu diziler
diziTek=np.array([1,2,3,4])
print(diziTek)

[1 2 3 4]


In [7]:
#Çift Boyutlu diziler
diziCift=np.array([[2,4,6],[1,3,5]])
print(diziCift)

[[2 4 6]
 [1 3 5]]


In [8]:
#3 boyutlu diziler
diziUcBoyut=np.array([[[1,2,3],[4,5,6]],[[10,11,12],[13,14,15]]])
print(diziUcBoyut)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]]


In [10]:
print(diziSifir.ndim)
print(diziTek.ndim)
print(diziCift.ndim)
print(diziUcBoyut.ndim)
#Bir dizinin boyutunu öğrenmek için ndim özelliği kullanılır...

0
1
2
3


In [15]:
bilgi=np.array([10,12,14,16], ndmin=2)
print(bilgi)
print('Dizinin boyut sayısı : ', bilgi.ndim)

[[10 12 14 16]]
Dizinin boyut sayısı :  2


In [18]:
sayilar=np.array([1,3,5,7])
print(sayilar[0])
print(sayilar[3])
print(sayilar[1]+sayilar[3])

1
7
10


In [22]:
sayilarIkı=np.array([[2,4,6],[1,3,5]])
print(sayilarIkı[0,0]) # 1 .dizinin ilk elemanı
print(sayilarIkı[1,2]) # 2 .dizinin 3.elemanı

2
5


In [25]:
sayilarUc=np.array([[[1,2,3],[4,5,6]],[[10,11,12],[13,14,15]]])
print(sayilarUc)
print(sayilarUc[0,1,1])
print(sayilarUc[1,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]]
5
15


In [30]:
sayilarIkı=np.array([[2,4,6],[1,3,5]])
print(sayilarIkı[1,-2])
print(sayilarIkı[0,-3])

3
2


In [41]:
diziTek=np.array([1,2,3,4,5,6,7])
print(diziTek[0:2])
print(diziTek[2:])
print(diziTek[:5])
print(diziTek[::2])
print(diziTek[1::2])
print(diziTek[-4:-2])

[1 2]
[3 4 5 6 7]
[1 2 3 4 5]
[1 3 5 7]
[2 4 6]
[4 5]


In [51]:
ikiBoyutlu=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(ikiBoyutlu[1,1:3]) #2.elemanın indeksi 1 ve 2 olanları çeker...
print(ikiBoyutlu[0:2,2])# her iki elemanının 3.elemanlarını çeker...
print(ikiBoyutlu[0:2,1:3]) # her iki elemanın 2 ve 3 . elemanlarını alır...
print(ikiBoyutlu[:,2])

[7 8]
[3 8]
[[2 3]
 [7 8]]
[3 8]


In [61]:
print(np.arange(0,101,5)) #np.arange(başlangıç, bitiş, artış)
print(np.arange(10))
print(np.arange(1,10))

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [63]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
np.random.randn(5).tolist()

[-0.12150837993775081,
 0.046660125306653,
 -2.3212300296988335,
 1.5797504512579574,
 0.3247983909612264]

In [72]:
np.random.randint(5,50)

45

In [84]:
rastgeleSayilar=np.random.randint(1,100,5)

In [85]:
print(rastgeleSayilar)

[46 31  9 79 51]


In [86]:
rastgeleSayilar.max()

79

In [87]:
rastgeleSayilar.min()

9

In [88]:
rastgeleSayilar.mean()

43.2

In [89]:
rastgeleSayilar.argmax()

3

In [90]:
rastgeleSayilar.argmin()

2

In [92]:
randomList=np.random.randint(0,100,20)
print(randomList)

[52  5 53 54 34 62 79 18 59 42 60 43 26 15 54 84 39 69 95 11]


In [98]:
random2List=randomList.reshape(5,4)
print(random2List)
print(type(random2List))
print(random2List.ndim)
print(randomList)
print(type(randomList))
print(randomList.ndim)

[[52  5 53 54]
 [34 62 79 18]
 [59 42 60 43]
 [26 15 54 84]
 [39 69 95 11]]
<class 'numpy.ndarray'>
2
[52  5 53 54 34 62 79 18 59 42 60 43 26 15 54 84 39 69 95 11]
<class 'numpy.ndarray'>
1


In [101]:
import pandas as pd
data=np.array(['a','b','c'])
Series=pd.Series(data,[10,11,12])
print(Series)

10    a
11    b
12    c
dtype: object


In [102]:
dict={'Bilgisayar':101, 'Elektrik':201,'Pazarlama':301}
Series1=pd.Series(dict)
print(Series1)

Bilgisayar    101
Elektrik      201
Pazarlama     301
dtype: int64


In [ ]:
KAYNAKÇA

https://www.datasciencearth.com/numpya-giris-bolum-6/

https://github.com/zekkontro/python-veri-bilimi/blob/main/numpy.ipynb

https://medium.com/deep-learning-turkiye/adan-z-ye-pandas-tutoriali-ba%C5%9Flang%C4%B1%C3%A7-ve-orta-seviye-4edf0094e0d5